"""Nightshift — nightly background processing and auto-memory extraction.

Runs as a daemon thread started in the FastAPI lifespan.  Wakes at the
configured hour (default 03:00 local time), iterates documents that have
few knowledge items, re-runs rule-based harvest (and optionally LLM
harvest if enabled), then writes a markdown Night Report to data/nightshift/.
"""
from __future__ import annotations

import logging
import os
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from orivellum.database.db import OrivellumDB
    from orivellum.configuration.config import OrivellumConfig

logger = logging.getLogger("orivellum.nightshift")

# Re-process docs whose knowledge count is below this threshold
_MIN_KNOWLEDGE_ITEMS = 3
# Max docs processed per run (safety valve)
_MAX_DOCS_PER_RUN = 20


def _get_docs_needing_work(db: "OrivellumDB") -> list[dict]:
    """Return ready documents that have fewer than _MIN_KNOWLEDGE_ITEMS knowledge entries."""
    with db._lock:
        rows = db._conn.execute(
            """SELECT d.id, d.work_id, d.title, d.source,
                      COUNT(k.id) AS kcount
               FROM documents d
               LEFT JOIN knowledge k ON k.source_doc_id = d.id
               WHERE d.readiness = 'ready'
               GROUP BY d.id
               HAVING kcount < ?
               ORDER BY d.created_at DESC
               LIMIT ?""",
            (_MIN_KNOWLEDGE_ITEMS, _MAX_DOCS_PER_RUN),
        ).fetchall()
    return [dict(r) for r in rows]


def _record_run(db: "OrivellumDB", docs_processed: int, items_added: int, report_path: str | None) -> None:
    run_id = str(uuid.uuid4())
    now    = datetime.now(timezone.utc).isoformat()
    with db._lock:
        try:
            db._conn.execute(
                "INSERT OR REPLACE INTO nightshift_runs(id,ran_at,docs_processed,items_added,report_path) VALUES(?,?,?,?,?)",
                (run_id, now, docs_processed, items_added, report_path),
            )
            db._conn.commit()
        except Exception as exc:
            logger.warning("Could not record nightshift run: %s", exc)


def _write_report(data_dir: Path, date_str: str, items: list[str]) -> str:
    report_dir = data_dir / "nightshift"
    report_dir.mkdir(parents=True, exist_ok=True)
    path = report_dir / f"{date_str}.md"
    header = f"# Night Report — {date_str}\n\nGenerated by Orivellum Nightshift.\n\n"
    body   = "\n".join(f"- {line}" for line in items) if items else "_Nothing to report._"
    path.write_text(header + body + "\n", encoding="utf-8")
    return str(path)


def run_nightshift(db: "OrivellumDB", cfg: "OrivellumConfig") -> None:
    """Execute one nightshift pass synchronously.  Called by the daemon thread."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    logger.info("Nightshift starting for %s", date_str)

    docs = _get_docs_needing_work(db)
    if not docs:
        logger.info("Nightshift: no documents need re-processing — sleeping")
        _record_run(db, 0, 0, None)
        return

    from orivellum.capabilities.knowledge_harvest import harvest
    items_added   = 0
    report_lines: list[str] = []
    ai_enabled    = db.get_setting("ai_extraction_enabled", "false").lower() == "true"

    from orivellum.capabilities.extraction import ExtractionResult, PageSegment

    for doc in docs:
        doc_id  = doc["id"]
        work_id = doc.get("work_id")
        title   = doc.get("title") or doc.get("source") or doc_id
        try:
            with db._lock:
                chunks_row = db._conn.execute(
                    "SELECT text FROM chunks WHERE doc_id=? ORDER BY position LIMIT 30", (doc_id,)
                ).fetchall()
            full_text = "\n".join(r["text"] for r in chunks_row)
            if not full_text.strip():
                logger.debug(
                    "Nightshift: skipping %s — no extractable text in chunks (sparse or image-only doc)",
                    doc_id,
                )
                report_lines.append(f"{title}: skipped — no text in chunks")
                continue

            # Reconstruct a minimal ExtractionResult so harvest() and llm_harvest()
            # receive the correct type (they expect ExtractionResult, not raw text).
            doc_info = db.get_document(doc_id)
            doc_kind = (doc_info or {}).get("kind") or "text"
            pages = [
                PageSegment(page=i + 1, text=r["text"])
                for i, r in enumerate(chunks_row)
            ]
            result = ExtractionResult(
                kind=doc_kind,
                full_text=full_text,
                word_count=len(full_text.split()),
                pages=pages,
            )

            before = len(db.list_knowledge(work_id=work_id, limit=500))
            harvest(result, doc_id=doc_id, work_id=work_id, doc_title=title, db=db)

            if ai_enabled:
                try:
                    from orivellum.capabilities.knowledge_harvest import llm_harvest
                    llm_harvest(result, doc_id=doc_id, work_id=work_id,
                                doc_title=title, db=db)
                except Exception as ai_exc:
                    logger.warning("Nightshift LLM harvest failed for %s: %s", doc_id, ai_exc)

            after  = len(db.list_knowledge(work_id=work_id, limit=500))
            added  = max(0, after - before)
            items_added += added
            report_lines.append(f"{title}: +{added} knowledge items")
        except Exception as exc:
            logger.warning("Nightshift failed for doc %s: %s", doc_id, exc)
            report_lines.append(f"{title}: ERROR — {exc}")

    report_path = _write_report(Path(cfg.data_dir), date_str, report_lines)
    _record_run(db, len(docs), items_added, report_path)
    logger.info("Nightshift complete — processed %d docs, added %d items", len(docs), items_added)


def start_nightshift_daemon(db: "OrivellumDB", cfg: "OrivellumConfig") -> threading.Thread:
    """Start the nightshift daemon thread.  Returns the thread (daemon=True)."""
    nightshift_hour = int(db.get_setting("nightshift_hour", "3"))

    def _loop():
        logger.info("Nightshift daemon ready (fires at %02d:00 local time)", nightshift_hour)
        while True:
            now  = datetime.now()
            # Sleep until the next occurrence of nightshift_hour:00
            target = now.replace(hour=nightshift_hour, minute=0, second=0, microsecond=0)
            if target <= now:
                target = target.replace(day=target.day + 1)
            wait_secs = (target - now).total_seconds()
            logger.debug("Nightshift sleeping %.0f s until %s", wait_secs, target.isoformat())
            time.sleep(max(wait_secs, 1))

            enabled = db.get_setting("nightshift_enabled", "true").lower() == "true"
            if enabled:
                try:
                    run_nightshift(db, cfg)
                except Exception as exc:
                    logger.error("Nightshift run crashed: %s", exc)
            else:
                logger.info("Nightshift disabled — skipping run")

    t = threading.Thread(target=_loop, name="orivellum-nightshift", daemon=True)
    t.start()
    return t
